### ISSUE TITLE
fargate job runners on EKS could not resolve host: gitlab.com 

### ISSUE THREAD

**Issue by neilkuan** [pahud/cdk-gitlab#27]
### When use fargate runner run gitlab pipeline job, The job will occur error. 
![photo_2020-11-16 11 42 49](https://user-images.githubusercontent.com/46012524/99210519-f62a2400-2800-11eb-9af2-b2a6c39cf8ee.jpeg)

### Use EC2 node run gitlab pipeline job, The job will success.
![photo_2020-11-16 11 42 53](https://user-images.githubusercontent.com/46012524/99210525-f9bdab00-2800-11eb-8c2c-ffb742ec9aad.jpeg)

That job `gitlab-ci.yaml` like this
```yaml
stages:
  - build
  - deploy
build-job:
  stage: build
  image: 
    name: alpine:3.11
    entrypoint: [""]
  tags:
    - runner
    - eks
    - fargate
  script:
    - echo "hello world"
    - sleep 20
  rules:
    - changes:
        - Dockerfile
```
